name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ laundry@195.14.122.183:/opt/flask_app

      - name: Restart Flask App
        run: |
          ssh -o StrictHostKeyChecking=no laundry@195.14.122.183 'export SUDO_ASKPASS=/usr/local/bin/mysudopass && sudo -A /bin/systemctl restart flask-app'
